services:
  - type: web
    name: glimpse-backend
    runtime: node
    rootDir: Glimpse_backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: GEMINI_BASE_URL
        value: https://generativelanguage.googleapis.com/v1beta
